### ISSUE TITLE
Markdown中のTwitter埋め込みが表示されない

### ISSUE THREAD

**Issue by yumcyaWiz** [TUS-OSK/oskt.us#119]
https://www.gatsbyjs.com/plugins/gatsby-plugin-twitter/ みたいにできると良さげ
各ページの`<head>`中にhttps://platform.twitter.com/widgets.js を埋め込むだけでいけそう?

**Comment by momoogles** [comment]
https://github.com/TUS-OSK/oskt.us/pull/115/commits/20b10b94ac60012671e68707bcf82927260093e3
こちら本日入りました！報告ありがとうございます！！
