### ISSUE TITLE
トップページの講義班のリンクが2019年度になってる

### ISSUE THREAD

**Issue by JF1HNL** [TUS-OSK/oskt.us#98]
https://github.com/TUS-OSK/oskt.us/blob/3b3e18fd9ae5b0e420a3d4d182a586769d49c164/view/schedule.js#L33
ここを編集する

**Comment by momoogles** [comment]
https://github.com/TUS-OSK/oskt.us/issues/103

リニューアルでこのリンクを無くしました。ここで修正することにします
